# Kafka image

FROM confluentinc/cp-kafka:latest

ENV KAFKA_BROKER_ID=1
ENV KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
ENV KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:29092
ENV KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
ENV KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1

EXPOSE 29092

CMD ["/etc/confluent/docker/run"]

# ZooKeeper image
FROM zookeeper:latest

ENV ZOOKEEPER_CLIENT_PORT=2181
ENV ZOOKEEPER_TICK_TIME=2000

EXPOSE 2181

CMD ["zkServer.sh", "start-foreground"]
