package com.stack.company.service;

import org.junit.jupiter.api.extension.ExtensionContext;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.ArgumentsProvider;

import java.util.stream.Stream;

public class InvalidEmailProvider
        implements ArgumentsProvider {
    @Override
    public Stream<? extends Arguments> provideArguments(ExtensionContext context) {
        return Stream.of(
                Arguments.of("longemail.@i.ua"),
                Arguments.of("1234567890@host.com"),
                Arguments.of("123longemail.@google.com"),
                Arguments.of("longemail123.@google.com"),
                Arguments.of("email..email@google.com"),
                Arguments.of("email...email@google.com"),
                Arguments.of(" "),
                Arguments.of(""),
                Arguments.of("a@b.c"),
                Arguments.of(" @.ua"),
                Arguments.of(" @i.ua"),
                Arguments.of("a@ .ua"),
                Arguments.of("email@"),
                Arguments.of("email@u"),
                Arguments.of("email.com"),
                Arguments.of("email@i.u"),
                Arguments.of("email@1i.u"),
                Arguments.of("email@i..u"),
                Arguments.of("1mail@i.ua"),
                Arguments.of("mail1@i.ua"),
                Arguments.of("now.1@i.ua"),
                Arguments.of("email@.com"),
                Arguments.of(",email@i.com"),
                Arguments.of("!email@i.com"),
                Arguments.of("@email@i.com"),
                Arguments.of("a@email@i.com"),
                Arguments.of("email@.com"),
                Arguments.of("@email.com"),
                Arguments.of("email@.com."),
                Arguments.of("1email@.com."),
                Arguments.of("e@i.ua"),
                Arguments.of("+email@i.com"),
                Arguments.of("-email@i.ua"),
                Arguments.of("&email@i.ua"),
                Arguments.of("*email@i.ua"),
                Arguments.of("_email@i.ua"),
                Arguments.of("+email@i.ua"),
                Arguments.of("email@1.ua"),
                Arguments.of("email@11.ua"),
                Arguments.of("123@i.ua"),
                Arguments.of("email@-google.com"),
                Arguments.of("email+tag@google.com"),
                Arguments.of("email@google-.com"),
                Arguments.of("_______@google.com"),
                Arguments.of("email@-google.com"),
                Arguments.of("email@google-.com"),
                Arguments.of("email+@i.ua"),
                Arguments.of("email&@i.ua"),
                Arguments.of("email*@i.ua"),
                Arguments.of("email_@i.ua"),
                Arguments.of("email@i.12"),
                Arguments.of("!email@i.ua"),
                Arguments.of("@email@i.ua"),
                Arguments.of("#email@i.ua"),
                Arguments.of("$email@i.ua"),
                Arguments.of("%email@i.ua"),
                Arguments.of("^email@i.ua"),
                Arguments.of(")email@i.ua"),
                Arguments.of("=email@i.ua"),
                Arguments.of("{email@i.ua"),
                Arguments.of("}email@i.ua"),
                Arguments.of("[email@i.ua"),
                Arguments.of("]email@i.ua"),
                Arguments.of(",email@i.ua"),
                Arguments.of("<email@i.ua"),
                Arguments.of(".email@i.ua"),
                Arguments.of("/email@i.ua"),
                Arguments.of(">email@i.ua"),
                Arguments.of("|email@i.ua"),
                Arguments.of("'email@i.ua"),
                Arguments.of(":email@i.ua"),
                Arguments.of("\"email@i.ua"),
                Arguments.of("\nemail@i.ua"),
                Arguments.of("\temail@i.ua"),
                Arguments.of(":email@i.ua"),
                Arguments.of(";email@i.ua"),
                Arguments.of(":email@i.ua"),
                Arguments.of("email/@i.ua"),
                Arguments.of("email|@i.ua"),
                Arguments.of("email'@i.ua"),
                Arguments.of("user123@google.google123"),
                Arguments.of("user-123@google.com"),
                Arguments.of("user_123@google.com"),
                Arguments.of("firstname+lastname@google.com"),
                Arguments.of("firstname-lastname@google.com"),
                Arguments.of("verylongemailaddresswithmorethan30charactersinlocalpart@google.com"),
                // Invalid: Username with short length
                Arguments.of("email!@i.ua"),
                Arguments.of("email$@i.ua"),
                Arguments.of("email%@i.ua"),
                Arguments.of("email^@i.ua"),
                Arguments.of("email=@i.ua"),
                Arguments.of("email{@i.ua"),
                Arguments.of("email}@i.ua"),
                Arguments.of("email#@i.ua"),
                Arguments.of("email[@i.ua"),
                Arguments.of("email]@i.ua"),
                Arguments.of("email,@i.ua"),
                Arguments.of("email)@i.ua"),
                Arguments.of("email<@i.ua"),
                Arguments.of("email:@i.ua"),
                Arguments.of("email>@i.ua"),
                Arguments.of("email\t@i.ua"),
                Arguments.of("email\n@i.ua"),
                Arguments.of("email:@i.ua"),
                Arguments.of("email;@i.ua"),
                Arguments.of("email:@i.ua"),
                Arguments.of("email@@i.ua"),
                Arguments.of("email 123@i.ua"),
                Arguments.of("email.email@com"),
                Arguments.of("email.email@ex.c"),
                Arguments.of("email.email@.com"),
                Arguments.of("email.google.com"),
                Arguments.of(".email@google.com"),
                Arguments.of("email email@google.com"),
                Arguments.of("email@127.0.0.1"),
                Arguments.of("email@google"),
                Arguments.of("email@google..com"),
                Arguments.of("Abc..123@google.com"),
                Arguments.of("email@123.123.123.123"),
                Arguments.of("email@111.222.333.44444"),
                Arguments.of("email@[123.123.123.123]"),
                Arguments.of("email@.com"),
                Arguments.of("email@google."),
                Arguments.of("email@google..com"),
                Arguments.of(".email@google.com"),
                Arguments.of("email@.google.com"),
                Arguments.of("email@google..com"),
                Arguments.of("email@google..sun.google.com"),
                Arguments.of("short@0372.ua"),
                Arguments.of("short@google.com"),
                Arguments.of("short@google.com"),
                Arguments.of("short@google.name"),
                Arguments.of("short@google.co.jp"),
                Arguments.of("short@google.ua.com"),
                Arguments.of("short@google.museum"),
                Arguments.of("short@google-one.com"),
                Arguments.of("email@"),
                Arguments.of("email@.com."),
                Arguments.of("email@com."),
                Arguments.of("email@com.."),
                Arguments.of("email..@google.com"),
                Arguments.of("email@.google.com"),
                Arguments.of("email@..google.com"),
                Arguments.of("email@.google.com."),
                Arguments.of("email@..google.com."),
                Arguments.of("email@.google.com.."),
                Arguments.of("email@..google.com.."),
                Arguments.of("email@google@google.com"),
                Arguments.of("email@google.com@google.com"),
                Arguments.of("email@google.com@google.com@google.com"),
                Arguments.of("email@google@google@google.com"),
                Arguments.of("email@google@google@google@google.com"),
                Arguments.of("a".repeat(256)),
                Arguments.of("@google.com"),
                Arguments.of("a".repeat(255)),
                Arguments.of("google"),
                Arguments.of("google."),
                Arguments.of(".com"),
                // Invalid: Domain with special characters
                Arguments.of("long.email@google..com"),
                Arguments.of("long.email@-google-.com"),
                Arguments.of("long.email@-google.+.com"),
                Arguments.of("long.email@google+.com"),
                Arguments.of("long.email@-google=.com"),
                Arguments.of("long.email@.google.com"),
                Arguments.of("long.email@,google,com"),
                Arguments.of("long.email@google,com"),
                Arguments.of("long.email@google>com"),
                Arguments.of("long.email@google?com"),
                Arguments.of("long.email@google/com"),
                Arguments.of("long.email@googlecom"),
                Arguments.of("missingdot@com"),
                Arguments.of("missingatgmail.com"),
                Arguments.of("invalid..domain@google.com"),
                Arguments.of("domain.com@google"),
                Arguments.of("domain@.com"),
                Arguments.of("domain@com."),
                Arguments.of("domain@google-.com"),
                Arguments.of("domain@-google.com"),
                Arguments.of("domain@.com"),
                Arguments.of("domain@google..com"),
                Arguments.of("domain@.google.com"),
                Arguments.of("domain@_google.com"),
                Arguments.of("domain@exa_mple.com"),
                Arguments.of("domain@google.c_om"),
                Arguments.of("long.email@google-.com"),
                Arguments.of("long.email@-google.com"),
                Arguments.of("long.email@google.com-"),
                Arguments.of("long.email@google.-com"),
                Arguments.of("long.email@google-.com."),
                Arguments.of("long.email@google.com."),
                Arguments.of("long.email@google..com."),
                Arguments.of("long.email@google.com.."),
                Arguments.of("long.email@google.-com."),
                Arguments.of("long.email@google-.com.."),
                Arguments.of("long.email@google.com.-"),
                Arguments.of("long.email@!google.com..-"),
                Arguments.of("long.email@@google..com"),
                Arguments.of("long.email@#google-.com"),
                Arguments.of("long.email@$google.com"),
                Arguments.of("long.email@%google.com-"),
                Arguments.of("long.email@^google.-com"),
                Arguments.of("long.email@*google-.com."),
                Arguments.of("long.email@(google.com."),
                Arguments.of("long.email@)google..com."),
                Arguments.of("long.email@_google.com.."),
                Arguments.of("long.email@+google.-com."),
                Arguments.of("long.email@<google-.com.."),
                Arguments.of("long.email@>google.com.-"),
                Arguments.of("long.email@>google.com..-"),
                Arguments.of("email@google.com"),
                Arguments.of("email@google..com"),
                Arguments.of("email@google@com"),
                Arguments.of("email@google@com."),
                Arguments.of("email@google.com."),
                Arguments.of("email@google.com.."),
                Arguments.of("email@google.com@"),
                Arguments.of("email@google.com@."),
                Arguments.of("email@google.com@.."),
                Arguments.of("email@google.com@com"),
                Arguments.of("email@google.com@com."),
                Arguments.of("email@google.com@com.."),
                Arguments.of("email@google.com@.com"),
                Arguments.of("email@google.com@..com"),
                Arguments.of("email@google.com@com.com"),
                Arguments.of("email@google.com@com.com."),
                Arguments.of("email@google.com@com.com.."),
                // Invalid: Missing username
                Arguments.of("@google..com"),
                Arguments.of("@google-.com"),
                Arguments.of("@-google.com"),
                Arguments.of("@google.com-"),
                Arguments.of("@google.-com"),
                Arguments.of("@google-.com."),
                Arguments.of("@google.com."),
                // Invalid: Missing username with @
                Arguments.of("google..com"),
                Arguments.of("google-.com"),
                Arguments.of("-google.com"),
                Arguments.of("google.com-"),
                Arguments.of("google.-com"),
                Arguments.of("google-.com."),
                Arguments.of("google.com."),
                Arguments.of("google..com."),
                Arguments.of("google.com.."),
                Arguments.of("google.-com."),
                Arguments.of("google-.com.."),
                Arguments.of("google.com.-"),
                Arguments.of("google.com..-"),
                // Invalid: Missing domain
                Arguments.of("1234567890"),
                Arguments.of("12345678901"),
                Arguments.of("123456789a"),
                Arguments.of("123456789A"),
                Arguments.of("long..email"),
                Arguments.of(".long.email"),
                Arguments.of("long.email"),
                Arguments.of("long.email"),
                Arguments.of("long.email1"),
                Arguments.of("long.email.1"),
                Arguments.of("long.email.1."),
                Arguments.of("long.email..1"),
                Arguments.of("long.email.1.."),
                Arguments.of("long.email..1."),
                Arguments.of("long.email.1..2"),
                Arguments.of("long.email..1..2"),
                Arguments.of("long.email.1..2."),
                Arguments.of("long.email..1..2."),
                Arguments.of("long.email.1..2.."),
                Arguments.of("long.email..1..2.."),
                // Invalid: Missing @ symbol
                Arguments.of("invalid-email"),
                Arguments.of("noatsymbol.google.com"),
                Arguments.of("missingAtSymbol.com"),
                Arguments.of("at@symbolmissing.com"),
                Arguments.of("missingAtSymbolNoDomain"),
                // Invalid: Missing domain
                Arguments.of("username@"),
                Arguments.of("username@."),
                Arguments.of("username@.com"),
                Arguments.of("username@.google"),
                Arguments.of("username@com"),
                // Invalid: Missing username
                Arguments.of("@domain.com"),
                Arguments.of("@domain"),
                Arguments.of("@domain."),
                Arguments.of("@.com"),
                Arguments.of("@.google"),
                // Invalid: Consecutive dots in username
                Arguments.of("user..name@google.com"),
                Arguments.of("user...name@google.com"),
                Arguments.of("user....name@google.com"),
                Arguments.of("user.....name@google.com"),
                Arguments.of("user......name@google.com"),
                // Invalid: Consecutive dots in domain
                Arguments.of("username@google..com"),
                Arguments.of("username@google...com"),
                Arguments.of("username@google....com"),
                Arguments.of("username@google.....com"),
                Arguments.of("username@google......com"),
                // Invalid: Top-level domain less than two letters
                Arguments.of("username@google.c"),
                Arguments.of("username@google.a"),
                Arguments.of("username@google. "),
                // Invalid: Domain with less than two levels
                Arguments.of("username@e"),
                Arguments.of("username@e."),
                Arguments.of("username@e.."),
                Arguments.of("username@e..f"),
                Arguments.of("username@e.f."),
                // Invalid: Missing domain levels
                Arguments.of("username@google"),
                Arguments.of("username@google."),
                // Invalid: Top-level domain less than two letters
                Arguments.of("username@google.c"),
                Arguments.of("username@google.a"),
                // Combining both scenarios
                Arguments.of("username@google"),
                Arguments.of("username@google."),
                Arguments.of("username@google.c"),
                Arguments.of("username@google.c"),
                Arguments.of("username@google.a"),
                Arguments.of("user@google.ab"),
                Arguments.of("user@google.abc"),
                Arguments.of("user@google.abcd")
        );
    }
}
